Repository CitadelCore/DescentPacks, pull requests merged in 2019-07, with the labels that each got.

#40 Add hardened glass recipes
  descentfrozenhell/scripts/thermaldynamics.zs
Labels: recipe

#49 Remove matterlink configuration
  descentfrozenhell/config/matterlink/commands.hjson
  descentfrozenhell/config/matterlink/identities.hjson
  descentfrozenhell/config/matterlink/matterlink.hjson
  descentfrozenhell/config/matterlink/permissions.hjson
Labels: server

#54 Removed Tough Expansion and library
  descentfrozenhell/config/ToughExpansion.cfg
  descentfrozenhell/mods/p455w0rds-library.lock.hjson
  descentfrozenhell/mods/tough-expansion.lock.hjson
  descentfrozenhell/scripts/toughasnails.zs
  packs/descentfrozenhell.voodoo.kts
Labels: bug, high priority

#59 Enable ProjectRed retrogen and fix recipes
  descentfrozenhell/config/ProjectRed.cfg
  descentfrozenhell/descentfrozenhell.lock.pack.hjson
  descentfrozenhell/mods/autoreglib.lock.hjson
  descentfrozenhell/mods/charset-audio.lock.hjson
  descentfrozenhell/mods/charset-immersion.lock.hjson
  descentfrozenhell/mods/charset-lib.lock.hjson
  descentfrozenhell/mods/charset-tablet.lock.hjson
  descentfrozenhell/mods/charset-tools.lock.hjson
  descentfrozenhell/mods/charset-tweaks.lock.hjson
  descentfrozenhell/mods/charsetpatches.lock.hjson
  descentfrozenhell/mods/gravestone-mod.lock.hjson
  descentfrozenhell/mods/industrial-foregoing.lock.hjson
  descentfrozenhell/mods/project-red-base.lock.hjson
  descentfrozenhell/mods/project-red-compat.lock.hjson
  descentfrozenhell/mods/project-red-fabrication.lock.hjson
  descentfrozenhell/mods/project-red-integration.lock.hjson
  descentfrozenhell/mods/project-red-lighting.lock.hjson
  descentfrozenhell/scripts/betterwithmods.zs
  descentfrozenhell/scripts/extrautilities.zs
  descentfrozenhell/scripts/railcraft.zs
  descentfrozenhell/scripts/vanilla.zs
  packs/descentfrozenhell.voodoo.kts
Labels: bug
