Repository CitadelCore/DescentPacks, pull requests merged in 2020-04, with the labels that each got.

#103 Remove redundant test pack build
  azure-pipelines.yml
Labels: meta

#109 Added `Flagged`, a mod that adds animated flags.
  descentfrozenhell/mods/_CLIENT/dynamic-surroundings.lock.json
  descentfrozenhell/mods/endercore.lock.json
  descentfrozenhell/mods/flagged.lock.json
  descentfrozenhell/mods/inventory-tweaks.lock.json
  descentfrozenhell/mods/thermal-foundation.lock.json
  local/flagged-1.12.2-0.1.1.jar
  packs/descentfrozenhell.voodoo.kts
Labels: enhancement

#110 Descent: Frozen Hell - Version 1.6.2
  descentfrozenhell/config/chiselsandbits.cfg
  descentfrozenhell/config/ftbutilities.cfg
  descentfrozenhell/config/laser_drill_ores/default_ores.json
  descentfrozenhell/config/laser_drill_ores/other_ores.json
  descentfrozenhell/config/railcraft/ores/mine_zinc.cfg
  descentfrozenhell/config/thaumicaugmentation.cfg
  descentfrozenhell/descentfrozenhell.lock.pack.json
  descentfrozenhell/mods/creativecore.lock.json
  descentfrozenhell/mods/engineered-golems.lock.json
  descentfrozenhell/mods/expanded-arcanum.lock.json
  descentfrozenhell/mods/littletiles.lock.json
  descentfrozenhell/mods/stimmedcow-nomorerecipeconflict.lock.json
  descentfrozenhell/mods/thaumic-periphery.lock.json
  descentfrozenhell/mods/top-addons.lock.json
  descentfrozenhell/scripts/appeng.zs
  descentfrozenhell/scripts/extrautilities.zs
  descentfrozenhell/scripts/global.zs
  descentfrozenhell/scripts/immersiveengineering.zs
  descentfrozenhell/scripts/industrialforegoing.zs
  descentfrozenhell/scripts/projectred.zs
  descentfrozenhell/scripts/railcraft.zs
  descentfrozenhell/scripts/recipes.zs
  descentfrozenhell/scripts/thaumcraft.zs
  descentfrozenhell/scripts/vanilla.zs
  packs/descentfrozenhell.voodoo.kts
Labels: bug, enhancement, recipe

#112 Emergency commit to remove Flagged and Little Tiles
  descentfrozenhell/mods/creativecore.lock.json
  descentfrozenhell/mods/flagged.lock.json
  descentfrozenhell/mods/littletiles.lock.json
  local/flagged-1.12.2-0.1.1.jar
  packs/descentfrozenhell.voodoo.kts
Labels: emergency

#113 Disable crafting of unbreakable block
  descentfrozenhell/scripts/thaumcraft.zs
  local/flagged-1.12.2-0.1.1.jar
  packs/descentfrozenhell.voodoo.kts
Labels: bug, emergency
