Repository CitadelCore/DescentPacks, pull requests merged in 2021-03, with the labels that each got.

#171 Remove broken local jar
  afhtest/lock/0.0.4/lock.pack.json
  afhtest/lock/0.0.4/src.zip
  afhtest/v0.0.4.voodoo.json5
Labels: bug, client, emergency, high priority, meta

#176 add local file back, do not loose those zip files anymore ?
  .github/workflows/deploy.yml
  wrapper/wrapper.properties
Labels: meta, server

#185 Update voodoo and fix pack deployment
  .github/workflows/deploy.yml
  afhtest/modpack.meta.json5
  wrapper/wrapper.jar
  wrapper/wrapper.properties
Labels: meta

#193 Emergency Fix: Remove malisis mods that are crashing
  afhtest/latest.voodoo.json5
  afhtest/lock/0.0.5/local.zip
  afhtest/lock/0.0.5/lock.pack.json
  afhtest/lock/0.0.5/src.zip
  wrapper/wrapper.jar
  wrapper/wrapper.properties
Labels: bug, emergency, high priority
